_core:
  default_config_hash: w2HQYJGLG4-Mmk19eIIKgoXCiXEJm-NVSNhhv-VdpUI
langcode: pt-br
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://Group_0.png'
  use_default: false
bootstrap_barrio_library: production
bootstrap_barrio_source: '0'
bootstrap_barrio_fluid_container: 0
bootstrap_barrio_region_clean_top_header: 0
bootstrap_barrio_region_class_top_header: row
bootstrap_barrio_region_clean_content: 1
bootstrap_barrio_region_class_content: ''
bootstrap_barrio_sidebar_position: both
bootstrap_barrio_content_offset: 0
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_sidebar_first_width: 4
bootstrap_barrio_sidebar_first_offset: 0
bootstrap_barrio_sidebar_second_width: 3
bootstrap_barrio_sidebar_second_offset: 0
bootstrap_barrio_button: 1
bootstrap_barrio_button_size: ''
bootstrap_barrio_button_outline: 0
bootstrap_barrio_navbar_container: '0'
bootstrap_barrio_navbar_toggle: navbar-toggleable-lg
bootstrap_barrio_navbar_top_navbar: 0
bootstrap_barrio_navbar_top_class: ''
bootstrap_barrio_navbar_class: ''
bootstrap_barrio_navbar_top_position: ''
bootstrap_barrio_navbar_top_color: ''
bootstrap_barrio_navbar_top_background: ''
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: ''
bootstrap_barrio_navbar_background: ''
bootstrap_barrio_navbar_flyout: false
bootstrap_barrio_navbar_slide: false
bootstrap_barrio_messages_widget: alerts
bootstrap_barrio_navbar_top_affix: 0
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: ''
bootstrap_barrio_bootstrap_icons: 0
bootstrap_barrio_icons: ''
bootstrap_barrio_system_messages: messages_white
bootstrap_barrio_table_style: table-striped
bootstrap_barrio_table_hover: 1
bootstrap_barrio_table_head: ''
bootstrap_barrio_image_fluid: false
bootstrap_barrio_tabs_style: ''
bootstrap_barrio_region_clean_header_search: 0
bootstrap_barrio_region_class_header_search: row
bootstrap_barrio_region_clean_primary_navigation: 0
bootstrap_barrio_region_class_primary_navigation: row
bootstrap_barrio_region_clean_home: 0
bootstrap_barrio_region_class_home: row
bootstrap_barrio_region_clean_home_banner_cards: 0
bootstrap_barrio_region_class_home_banner_cards: row
bootstrap_barrio_region_clean_footer: 0
bootstrap_barrio_region_class_footer: row
bootstrap_barrio_region_clean_newsletter: 0
bootstrap_barrio_region_class_newsletter: row
bootstrap_barrio_region_clean_footer_right: 0
bootstrap_barrio_region_class_footer_right: row
bootstrap_barrio_hide_node_label: 0
bootstrap_barrio_navbar_offcanvas: ''
secondary_logo:
  - '175'
bootstrap_barrio_region_clean_footer_navigation: 0
bootstrap_barrio_region_class_footer_navigation: row
bootstrap_barrio_region_clean_footer_section: 0
bootstrap_barrio_region_class_footer_section: row
langcode: pt-br
