bootstrap_barrio_library: production
bootstrap_barrio_sidebar_position: both
bootstrap_barrio_navbar_toggle: navbar-toggleable-lg
bootstrap_barrio_messages_widget: alerts
bootstrap_barrio_system_messages: messages_white
bootstrap_barrio_table_style: table-striped
